### ISSUE TITLE
linux or windows build the project?

### ISSUE THREAD

**Issue by neolu** [wangyeee/autoquadfc#1]
linux or windows build the project?

**Comment by wangyeee** [comment]
I would suggest try building this on Linux or macOS if you have xcode installed. Theoretically this can also be compiled on windows if you install cygwin or mingw and other build tools.

Please also note that this project will not be updated from upstream. Take a look at another repo which is forked from upstream. The gcc version makefile is also there.
https://github.com/wangyeee/aq_flight_control
